### ISSUE TITLE
Criar novo fornecedor 

### ISSUE THREAD

**Issue by rog404** [TreinaDev/storage-td6#3]
Eu, como usuário, devo gerenciar fornecedores, para que possa cadastrar os produtos adequadamente no estoque.

Fornecedores devem ter:
- Razão social
- Nome fantasia
- Endereço completo
- CNPJ
- Outros dados (se necessário)

supplier
name
trade name
cnpj
[address] references

**Comment by glmsilva** [comment]
Eu, como usuário, devo gerenciar fornecedores, para que possa cadastras os produtos adequadamente no estoque.
